title: Generative AI and HCI
description: A CHI workshop to discuss how Generative AI systems can interact with humans usefully and safely.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima
plugins:
  - jekyll-feed

